# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

kodama_matrix_cpp <- function(data, spatial = NULL, W = NULL, constrain = NULL, fix = NULL, M = 100L, Tcycle = 20L, ncomp = 50L, landmarks = 10000L, splitting = 0L, n_cores = 4L, graph_neighbors = 100L, knn_k = 30L, spatial_resolution = 0.4, spatial_graph_mix = FALSE, spatial_constraint_mode = 0L, metric = "euclidean", classifier = "knn", backend = "cpu", seed = 1234L, progress = FALSE, apply_kodama_dissimilarity = TRUE) {
    .Call(`_kodamaR_kodama_matrix_cpp`, data, spatial, W, constrain, fix, M, Tcycle, ncomp, landmarks, splitting, n_cores, graph_neighbors, knn_k, spatial_resolution, spatial_graph_mix, spatial_constraint_mode, metric, classifier, backend, seed, progress, apply_kodama_dissimilarity)
}

kodama_matrix_graph_cpp <- function(indices, distances, data = NULL, spatial = NULL, W = NULL, constrain = NULL, fix = NULL, M = 100L, Tcycle = 20L, ncomp = 50L, landmarks = 10000L, splitting = 0L, n_cores = 4L, graph_neighbors = 100L, knn_k = 30L, spatial_resolution = 0.3, spatial_graph_mix = FALSE, spatial_constraint_mode = 0L, classifier = "knn", backend = "cpu", graph_feature_mode = "laplacian_self_tuning", graph_feature_components = 0L, graph_feature_steps = 3L, seed = 1234L, progress = FALSE, apply_kodama_dissimilarity = TRUE) {
    .Call(`_kodamaR_kodama_matrix_graph_cpp`, indices, distances, data, spatial, W, constrain, fix, M, Tcycle, ncomp, landmarks, splitting, n_cores, graph_neighbors, knn_k, spatial_resolution, spatial_graph_mix, spatial_constraint_mode, classifier, backend, graph_feature_mode, graph_feature_components, graph_feature_steps, seed, progress, apply_kodama_dissimilarity)
}

knncv_cpp <- function(data, labels, constrain = NULL, folds = 10L, stratified = TRUE, seed = 1L, k = 10L, metric = "cosine", backend = "cpu", n_threads = 1L, gpu_device = 0L) {
    .Call(`_kodamaR_knncv_cpp`, data, labels, constrain, folds, stratified, seed, k, metric, backend, n_threads, gpu_device)
}

plsldacv_cpp <- function(data, labels, constrain = NULL, folds = 10L, stratified = TRUE, seed = 1L, ncomp = 50L, center = TRUE, scale = TRUE, backend = "cpu", n_threads = 1L, gpu_device = 0L) {
    .Call(`_kodamaR_plsldacv_cpp`, data, labels, constrain, folds, stratified, seed, ncomp, center, scale, backend, n_threads, gpu_device)
}

core_knn_cpp <- function(data, starting_labels, constrain = NULL, fix = NULL, cycles = 100L, folds = 10L, stratified = TRUE, seed = 1L, k = 30L, metric = "euclidean", backend = "cpu", n_threads = 4L, gpu_device = 0L) {
    .Call(`_kodamaR_core_knn_cpp`, data, starting_labels, constrain, fix, cycles, folds, stratified, seed, k, metric, backend, n_threads, gpu_device)
}

core_plslda_cpp <- function(data, starting_labels, constrain = NULL, fix = NULL, cycles = 100L, folds = 10L, stratified = TRUE, seed = 1L, ncomp = 50L, backend = "cpu", n_threads = 4L, gpu_device = 0L) {
    .Call(`_kodamaR_core_plslda_cpp`, data, starting_labels, constrain, fix, cycles, folds, stratified, seed, ncomp, backend, n_threads, gpu_device)
}

kodama_knn_graph_cpp <- function(data, k = 30L, metric = "euclidean", backend = "cpu", n_threads = 4L, gpu_device = 0L) {
    .Call(`_kodamaR_kodama_knn_graph_cpp`, data, k, metric, backend, n_threads, gpu_device)
}

kodama_umap_cpp <- function(indices, distances, init = NULL, n_neighbors = 30L, n_epochs = 200L, learning_rate = 1.0, min_dist = 0.01, repulsion_strength = 1.0, negative_sample_rate = 5L, spectral_n_iter = 20L, n_threads = 1L, seed = 1234L, backend = "cpu", gpu_device = 0L) {
    .Call(`_kodamaR_kodama_umap_cpp`, indices, distances, init, n_neighbors, n_epochs, learning_rate, min_dist, repulsion_strength, negative_sample_rate, spectral_n_iter, n_threads, seed, backend, gpu_device)
}

kodama_opentsne_cpp <- function(indices, distances, init = NULL, n_neighbors = 0L, perplexity = 30.0, theta = 0.5, early_exaggeration_iter = 250L, n_iter = 500L, early_exaggeration = 12.0, exaggeration = 1.0, learning_rate = 0.0, learning_rate_auto = TRUE, initial_momentum = 0.8, final_momentum = 0.8, min_gain = 0.01, max_step_norm = 5.0, n_threads = 1L, seed = 4L, backend = "cpu", gpu_device = 0L) {
    .Call(`_kodamaR_kodama_opentsne_cpp`, indices, distances, init, n_neighbors, perplexity, theta, early_exaggeration_iter, n_iter, early_exaggeration, exaggeration, learning_rate, learning_rate_auto, initial_momentum, final_momentum, min_gain, max_step_norm, n_threads, seed, backend, gpu_device)
}

kodama_graph_cluster_cpp <- function(indices, distances, method = "louvain", backend = "cpu", weight = "distance", n_threads = 4L, n_runs = 1L, n_iterations = 10L, random_walk_steps = 4L, n_clusters = 0L, resolution = 1.0, resolution_init = 0.0, resolution_delta = 0.2, prune = 0.0, mutual = FALSE, seed = 1L, gpu_device = 0L) {
    .Call(`_kodamaR_kodama_graph_cluster_cpp`, indices, distances, method, backend, weight, n_threads, n_runs, n_iterations, random_walk_steps, n_clusters, resolution, resolution_init, resolution_delta, prune, mutual, seed, gpu_device)
}

kodama_embedding_cluster_cpp <- function(embedding, method = "louvain", backend = "cpu", graph_backend = "cpu", weight = "distance", metric = "euclidean", k = 30L, n_threads = 4L, n_runs = 1L, n_iterations = 10L, random_walk_steps = 4L, n_clusters = 0L, resolution = 1.0, resolution_init = 0.0, resolution_delta = 0.2, prune = 0.0, mutual = FALSE, seed = 1L, gpu_device = 0L) {
    .Call(`_kodamaR_kodama_embedding_cluster_cpp`, embedding, method, backend, graph_backend, weight, metric, k, n_threads, n_runs, n_iterations, random_walk_steps, n_clusters, resolution, resolution_init, resolution_delta, prune, mutual, seed, gpu_device)
}
