// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// kodama_matrix_cpp
Rcpp::List kodama_matrix_cpp(Rcpp::NumericMatrix data, Rcpp::Nullable<Rcpp::NumericMatrix> spatial, Rcpp::Nullable<Rcpp::IntegerVector> W, Rcpp::Nullable<Rcpp::IntegerVector> constrain, Rcpp::Nullable<Rcpp::IntegerVector> fix, int M, int Tcycle, int ncomp, int landmarks, int splitting, int n_cores, int graph_neighbors, int knn_k, double spatial_resolution, bool spatial_graph_mix, int spatial_constraint_mode, std::string metric, std::string classifier, std::string backend, int seed, bool progress, bool apply_kodama_dissimilarity);
RcppExport SEXP _kodamaR_kodama_matrix_cpp(SEXP dataSEXP, SEXP spatialSEXP, SEXP WSEXP, SEXP constrainSEXP, SEXP fixSEXP, SEXP MSEXP, SEXP TcycleSEXP, SEXP ncompSEXP, SEXP landmarksSEXP, SEXP splittingSEXP, SEXP n_coresSEXP, SEXP graph_neighborsSEXP, SEXP knn_kSEXP, SEXP spatial_resolutionSEXP, SEXP spatial_graph_mixSEXP, SEXP spatial_constraint_modeSEXP, SEXP metricSEXP, SEXP classifierSEXP, SEXP backendSEXP, SEXP seedSEXP, SEXP progressSEXP, SEXP apply_kodama_dissimilaritySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type data(dataSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::NumericMatrix> >::type spatial(spatialSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::IntegerVector> >::type W(WSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::IntegerVector> >::type constrain(constrainSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::IntegerVector> >::type fix(fixSEXP);
    Rcpp::traits::input_parameter< int >::type M(MSEXP);
    Rcpp::traits::input_parameter< int >::type Tcycle(TcycleSEXP);
    Rcpp::traits::input_parameter< int >::type ncomp(ncompSEXP);
    Rcpp::traits::input_parameter< int >::type landmarks(landmarksSEXP);
    Rcpp::traits::input_parameter< int >::type splitting(splittingSEXP);
    Rcpp::traits::input_parameter< int >::type n_cores(n_coresSEXP);
    Rcpp::traits::input_parameter< int >::type graph_neighbors(graph_neighborsSEXP);
    Rcpp::traits::input_parameter< int >::type knn_k(knn_kSEXP);
    Rcpp::traits::input_parameter< double >::type spatial_resolution(spatial_resolutionSEXP);
    Rcpp::traits::input_parameter< bool >::type spatial_graph_mix(spatial_graph_mixSEXP);
    Rcpp::traits::input_parameter< int >::type spatial_constraint_mode(spatial_constraint_modeSEXP);
    Rcpp::traits::input_parameter< std::string >::type metric(metricSEXP);
    Rcpp::traits::input_parameter< std::string >::type classifier(classifierSEXP);
    Rcpp::traits::input_parameter< std::string >::type backend(backendSEXP);
    Rcpp::traits::input_parameter< int >::type seed(seedSEXP);
    Rcpp::traits::input_parameter< bool >::type progress(progressSEXP);
    Rcpp::traits::input_parameter< bool >::type apply_kodama_dissimilarity(apply_kodama_dissimilaritySEXP);
    rcpp_result_gen = Rcpp::wrap(kodama_matrix_cpp(data, spatial, W, constrain, fix, M, Tcycle, ncomp, landmarks, splitting, n_cores, graph_neighbors, knn_k, spatial_resolution, spatial_graph_mix, spatial_constraint_mode, metric, classifier, backend, seed, progress, apply_kodama_dissimilarity));
    return rcpp_result_gen;
END_RCPP
}
// kodama_matrix_graph_cpp
Rcpp::List kodama_matrix_graph_cpp(Rcpp::IntegerMatrix indices, Rcpp::NumericMatrix distances, Rcpp::Nullable<Rcpp::NumericMatrix> data, Rcpp::Nullable<Rcpp::NumericMatrix> spatial, Rcpp::Nullable<Rcpp::IntegerVector> W, Rcpp::Nullable<Rcpp::IntegerVector> constrain, Rcpp::Nullable<Rcpp::IntegerVector> fix, int M, int Tcycle, int ncomp, int landmarks, int splitting, int n_cores, int graph_neighbors, int knn_k, double spatial_resolution, bool spatial_graph_mix, int spatial_constraint_mode, std::string classifier, std::string backend, std::string graph_feature_mode, int graph_feature_components, int graph_feature_steps, int seed, bool progress, bool apply_kodama_dissimilarity);
RcppExport SEXP _kodamaR_kodama_matrix_graph_cpp(SEXP indicesSEXP, SEXP distancesSEXP, SEXP dataSEXP, SEXP spatialSEXP, SEXP WSEXP, SEXP constrainSEXP, SEXP fixSEXP, SEXP MSEXP, SEXP TcycleSEXP, SEXP ncompSEXP, SEXP landmarksSEXP, SEXP splittingSEXP, SEXP n_coresSEXP, SEXP graph_neighborsSEXP, SEXP knn_kSEXP, SEXP spatial_resolutionSEXP, SEXP spatial_graph_mixSEXP, SEXP spatial_constraint_modeSEXP, SEXP classifierSEXP, SEXP backendSEXP, SEXP graph_feature_modeSEXP, SEXP graph_feature_componentsSEXP, SEXP graph_feature_stepsSEXP, SEXP seedSEXP, SEXP progressSEXP, SEXP apply_kodama_dissimilaritySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::IntegerMatrix >::type indices(indicesSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type distances(distancesSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::NumericMatrix> >::type data(dataSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::NumericMatrix> >::type spatial(spatialSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::IntegerVector> >::type W(WSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::IntegerVector> >::type constrain(constrainSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::IntegerVector> >::type fix(fixSEXP);
    Rcpp::traits::input_parameter< int >::type M(MSEXP);
    Rcpp::traits::input_parameter< int >::type Tcycle(TcycleSEXP);
    Rcpp::traits::input_parameter< int >::type ncomp(ncompSEXP);
    Rcpp::traits::input_parameter< int >::type landmarks(landmarksSEXP);
    Rcpp::traits::input_parameter< int >::type splitting(splittingSEXP);
    Rcpp::traits::input_parameter< int >::type n_cores(n_coresSEXP);
    Rcpp::traits::input_parameter< int >::type graph_neighbors(graph_neighborsSEXP);
    Rcpp::traits::input_parameter< int >::type knn_k(knn_kSEXP);
    Rcpp::traits::input_parameter< double >::type spatial_resolution(spatial_resolutionSEXP);
    Rcpp::traits::input_parameter< bool >::type spatial_graph_mix(spatial_graph_mixSEXP);
    Rcpp::traits::input_parameter< int >::type spatial_constraint_mode(spatial_constraint_modeSEXP);
    Rcpp::traits::input_parameter< std::string >::type classifier(classifierSEXP);
    Rcpp::traits::input_parameter< std::string >::type backend(backendSEXP);
    Rcpp::traits::input_parameter< std::string >::type graph_feature_mode(graph_feature_modeSEXP);
    Rcpp::traits::input_parameter< int >::type graph_feature_components(graph_feature_componentsSEXP);
    Rcpp::traits::input_parameter< int >::type graph_feature_steps(graph_feature_stepsSEXP);
    Rcpp::traits::input_parameter< int >::type seed(seedSEXP);
    Rcpp::traits::input_parameter< bool >::type progress(progressSEXP);
    Rcpp::traits::input_parameter< bool >::type apply_kodama_dissimilarity(apply_kodama_dissimilaritySEXP);
    rcpp_result_gen = Rcpp::wrap(kodama_matrix_graph_cpp(indices, distances, data, spatial, W, constrain, fix, M, Tcycle, ncomp, landmarks, splitting, n_cores, graph_neighbors, knn_k, spatial_resolution, spatial_graph_mix, spatial_constraint_mode, classifier, backend, graph_feature_mode, graph_feature_components, graph_feature_steps, seed, progress, apply_kodama_dissimilarity));
    return rcpp_result_gen;
END_RCPP
}
// knncv_cpp
Rcpp::List knncv_cpp(Rcpp::NumericMatrix data, Rcpp::IntegerVector labels, Rcpp::Nullable<Rcpp::IntegerVector> constrain, int folds, bool stratified, int seed, int k, std::string metric, std::string backend, int n_threads, int gpu_device);
RcppExport SEXP _kodamaR_knncv_cpp(SEXP dataSEXP, SEXP labelsSEXP, SEXP constrainSEXP, SEXP foldsSEXP, SEXP stratifiedSEXP, SEXP seedSEXP, SEXP kSEXP, SEXP metricSEXP, SEXP backendSEXP, SEXP n_threadsSEXP, SEXP gpu_deviceSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type data(dataSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type labels(labelsSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::IntegerVector> >::type constrain(constrainSEXP);
    Rcpp::traits::input_parameter< int >::type folds(foldsSEXP);
    Rcpp::traits::input_parameter< bool >::type stratified(stratifiedSEXP);
    Rcpp::traits::input_parameter< int >::type seed(seedSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    Rcpp::traits::input_parameter< std::string >::type metric(metricSEXP);
    Rcpp::traits::input_parameter< std::string >::type backend(backendSEXP);
    Rcpp::traits::input_parameter< int >::type n_threads(n_threadsSEXP);
    Rcpp::traits::input_parameter< int >::type gpu_device(gpu_deviceSEXP);
    rcpp_result_gen = Rcpp::wrap(knncv_cpp(data, labels, constrain, folds, stratified, seed, k, metric, backend, n_threads, gpu_device));
    return rcpp_result_gen;
END_RCPP
}
// plsldacv_cpp
Rcpp::List plsldacv_cpp(Rcpp::NumericMatrix data, Rcpp::IntegerVector labels, Rcpp::Nullable<Rcpp::IntegerVector> constrain, int folds, bool stratified, int seed, int ncomp, bool center, bool scale, std::string backend, int n_threads, int gpu_device);
RcppExport SEXP _kodamaR_plsldacv_cpp(SEXP dataSEXP, SEXP labelsSEXP, SEXP constrainSEXP, SEXP foldsSEXP, SEXP stratifiedSEXP, SEXP seedSEXP, SEXP ncompSEXP, SEXP centerSEXP, SEXP scaleSEXP, SEXP backendSEXP, SEXP n_threadsSEXP, SEXP gpu_deviceSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type data(dataSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type labels(labelsSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::IntegerVector> >::type constrain(constrainSEXP);
    Rcpp::traits::input_parameter< int >::type folds(foldsSEXP);
    Rcpp::traits::input_parameter< bool >::type stratified(stratifiedSEXP);
    Rcpp::traits::input_parameter< int >::type seed(seedSEXP);
    Rcpp::traits::input_parameter< int >::type ncomp(ncompSEXP);
    Rcpp::traits::input_parameter< bool >::type center(centerSEXP);
    Rcpp::traits::input_parameter< bool >::type scale(scaleSEXP);
    Rcpp::traits::input_parameter< std::string >::type backend(backendSEXP);
    Rcpp::traits::input_parameter< int >::type n_threads(n_threadsSEXP);
    Rcpp::traits::input_parameter< int >::type gpu_device(gpu_deviceSEXP);
    rcpp_result_gen = Rcpp::wrap(plsldacv_cpp(data, labels, constrain, folds, stratified, seed, ncomp, center, scale, backend, n_threads, gpu_device));
    return rcpp_result_gen;
END_RCPP
}
// core_knn_cpp
Rcpp::List core_knn_cpp(Rcpp::NumericMatrix data, Rcpp::IntegerVector starting_labels, Rcpp::Nullable<Rcpp::IntegerVector> constrain, Rcpp::Nullable<Rcpp::IntegerVector> fix, int cycles, int folds, bool stratified, int seed, int k, std::string metric, std::string backend, int n_threads, int gpu_device);
RcppExport SEXP _kodamaR_core_knn_cpp(SEXP dataSEXP, SEXP starting_labelsSEXP, SEXP constrainSEXP, SEXP fixSEXP, SEXP cyclesSEXP, SEXP foldsSEXP, SEXP stratifiedSEXP, SEXP seedSEXP, SEXP kSEXP, SEXP metricSEXP, SEXP backendSEXP, SEXP n_threadsSEXP, SEXP gpu_deviceSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type data(dataSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type starting_labels(starting_labelsSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::IntegerVector> >::type constrain(constrainSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::IntegerVector> >::type fix(fixSEXP);
    Rcpp::traits::input_parameter< int >::type cycles(cyclesSEXP);
    Rcpp::traits::input_parameter< int >::type folds(foldsSEXP);
    Rcpp::traits::input_parameter< bool >::type stratified(stratifiedSEXP);
    Rcpp::traits::input_parameter< int >::type seed(seedSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    Rcpp::traits::input_parameter< std::string >::type metric(metricSEXP);
    Rcpp::traits::input_parameter< std::string >::type backend(backendSEXP);
    Rcpp::traits::input_parameter< int >::type n_threads(n_threadsSEXP);
    Rcpp::traits::input_parameter< int >::type gpu_device(gpu_deviceSEXP);
    rcpp_result_gen = Rcpp::wrap(core_knn_cpp(data, starting_labels, constrain, fix, cycles, folds, stratified, seed, k, metric, backend, n_threads, gpu_device));
    return rcpp_result_gen;
END_RCPP
}
// core_plslda_cpp
Rcpp::List core_plslda_cpp(Rcpp::NumericMatrix data, Rcpp::IntegerVector starting_labels, Rcpp::Nullable<Rcpp::IntegerVector> constrain, Rcpp::Nullable<Rcpp::IntegerVector> fix, int cycles, int folds, bool stratified, int seed, int ncomp, std::string backend, int n_threads, int gpu_device);
RcppExport SEXP _kodamaR_core_plslda_cpp(SEXP dataSEXP, SEXP starting_labelsSEXP, SEXP constrainSEXP, SEXP fixSEXP, SEXP cyclesSEXP, SEXP foldsSEXP, SEXP stratifiedSEXP, SEXP seedSEXP, SEXP ncompSEXP, SEXP backendSEXP, SEXP n_threadsSEXP, SEXP gpu_deviceSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type data(dataSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type starting_labels(starting_labelsSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::IntegerVector> >::type constrain(constrainSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::IntegerVector> >::type fix(fixSEXP);
    Rcpp::traits::input_parameter< int >::type cycles(cyclesSEXP);
    Rcpp::traits::input_parameter< int >::type folds(foldsSEXP);
    Rcpp::traits::input_parameter< bool >::type stratified(stratifiedSEXP);
    Rcpp::traits::input_parameter< int >::type seed(seedSEXP);
    Rcpp::traits::input_parameter< int >::type ncomp(ncompSEXP);
    Rcpp::traits::input_parameter< std::string >::type backend(backendSEXP);
    Rcpp::traits::input_parameter< int >::type n_threads(n_threadsSEXP);
    Rcpp::traits::input_parameter< int >::type gpu_device(gpu_deviceSEXP);
    rcpp_result_gen = Rcpp::wrap(core_plslda_cpp(data, starting_labels, constrain, fix, cycles, folds, stratified, seed, ncomp, backend, n_threads, gpu_device));
    return rcpp_result_gen;
END_RCPP
}
// kodama_knn_graph_cpp
Rcpp::List kodama_knn_graph_cpp(Rcpp::NumericMatrix data, int k, std::string metric, std::string backend, int n_threads, int gpu_device);
RcppExport SEXP _kodamaR_kodama_knn_graph_cpp(SEXP dataSEXP, SEXP kSEXP, SEXP metricSEXP, SEXP backendSEXP, SEXP n_threadsSEXP, SEXP gpu_deviceSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type data(dataSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    Rcpp::traits::input_parameter< std::string >::type metric(metricSEXP);
    Rcpp::traits::input_parameter< std::string >::type backend(backendSEXP);
    Rcpp::traits::input_parameter< int >::type n_threads(n_threadsSEXP);
    Rcpp::traits::input_parameter< int >::type gpu_device(gpu_deviceSEXP);
    rcpp_result_gen = Rcpp::wrap(kodama_knn_graph_cpp(data, k, metric, backend, n_threads, gpu_device));
    return rcpp_result_gen;
END_RCPP
}
// kodama_umap_cpp
Rcpp::NumericMatrix kodama_umap_cpp(Rcpp::IntegerMatrix indices, Rcpp::NumericMatrix distances, Rcpp::Nullable<Rcpp::NumericMatrix> init, int n_neighbors, int n_epochs, double learning_rate, double min_dist, double repulsion_strength, int negative_sample_rate, int spectral_n_iter, int n_threads, int seed, std::string backend, int gpu_device);
RcppExport SEXP _kodamaR_kodama_umap_cpp(SEXP indicesSEXP, SEXP distancesSEXP, SEXP initSEXP, SEXP n_neighborsSEXP, SEXP n_epochsSEXP, SEXP learning_rateSEXP, SEXP min_distSEXP, SEXP repulsion_strengthSEXP, SEXP negative_sample_rateSEXP, SEXP spectral_n_iterSEXP, SEXP n_threadsSEXP, SEXP seedSEXP, SEXP backendSEXP, SEXP gpu_deviceSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::IntegerMatrix >::type indices(indicesSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type distances(distancesSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::NumericMatrix> >::type init(initSEXP);
    Rcpp::traits::input_parameter< int >::type n_neighbors(n_neighborsSEXP);
    Rcpp::traits::input_parameter< int >::type n_epochs(n_epochsSEXP);
    Rcpp::traits::input_parameter< double >::type learning_rate(learning_rateSEXP);
    Rcpp::traits::input_parameter< double >::type min_dist(min_distSEXP);
    Rcpp::traits::input_parameter< double >::type repulsion_strength(repulsion_strengthSEXP);
    Rcpp::traits::input_parameter< int >::type negative_sample_rate(negative_sample_rateSEXP);
    Rcpp::traits::input_parameter< int >::type spectral_n_iter(spectral_n_iterSEXP);
    Rcpp::traits::input_parameter< int >::type n_threads(n_threadsSEXP);
    Rcpp::traits::input_parameter< int >::type seed(seedSEXP);
    Rcpp::traits::input_parameter< std::string >::type backend(backendSEXP);
    Rcpp::traits::input_parameter< int >::type gpu_device(gpu_deviceSEXP);
    rcpp_result_gen = Rcpp::wrap(kodama_umap_cpp(indices, distances, init, n_neighbors, n_epochs, learning_rate, min_dist, repulsion_strength, negative_sample_rate, spectral_n_iter, n_threads, seed, backend, gpu_device));
    return rcpp_result_gen;
END_RCPP
}
// kodama_opentsne_cpp
Rcpp::NumericMatrix kodama_opentsne_cpp(Rcpp::IntegerMatrix indices, Rcpp::NumericMatrix distances, Rcpp::Nullable<Rcpp::NumericMatrix> init, int n_neighbors, double perplexity, double theta, int early_exaggeration_iter, int n_iter, double early_exaggeration, double exaggeration, double learning_rate, bool learning_rate_auto, double initial_momentum, double final_momentum, double min_gain, double max_step_norm, int n_threads, int seed, std::string backend, int gpu_device);
RcppExport SEXP _kodamaR_kodama_opentsne_cpp(SEXP indicesSEXP, SEXP distancesSEXP, SEXP initSEXP, SEXP n_neighborsSEXP, SEXP perplexitySEXP, SEXP thetaSEXP, SEXP early_exaggeration_iterSEXP, SEXP n_iterSEXP, SEXP early_exaggerationSEXP, SEXP exaggerationSEXP, SEXP learning_rateSEXP, SEXP learning_rate_autoSEXP, SEXP initial_momentumSEXP, SEXP final_momentumSEXP, SEXP min_gainSEXP, SEXP max_step_normSEXP, SEXP n_threadsSEXP, SEXP seedSEXP, SEXP backendSEXP, SEXP gpu_deviceSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::IntegerMatrix >::type indices(indicesSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type distances(distancesSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::NumericMatrix> >::type init(initSEXP);
    Rcpp::traits::input_parameter< int >::type n_neighbors(n_neighborsSEXP);
    Rcpp::traits::input_parameter< double >::type perplexity(perplexitySEXP);
    Rcpp::traits::input_parameter< double >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< int >::type early_exaggeration_iter(early_exaggeration_iterSEXP);
    Rcpp::traits::input_parameter< int >::type n_iter(n_iterSEXP);
    Rcpp::traits::input_parameter< double >::type early_exaggeration(early_exaggerationSEXP);
    Rcpp::traits::input_parameter< double >::type exaggeration(exaggerationSEXP);
    Rcpp::traits::input_parameter< double >::type learning_rate(learning_rateSEXP);
    Rcpp::traits::input_parameter< bool >::type learning_rate_auto(learning_rate_autoSEXP);
    Rcpp::traits::input_parameter< double >::type initial_momentum(initial_momentumSEXP);
    Rcpp::traits::input_parameter< double >::type final_momentum(final_momentumSEXP);
    Rcpp::traits::input_parameter< double >::type min_gain(min_gainSEXP);
    Rcpp::traits::input_parameter< double >::type max_step_norm(max_step_normSEXP);
    Rcpp::traits::input_parameter< int >::type n_threads(n_threadsSEXP);
    Rcpp::traits::input_parameter< int >::type seed(seedSEXP);
    Rcpp::traits::input_parameter< std::string >::type backend(backendSEXP);
    Rcpp::traits::input_parameter< int >::type gpu_device(gpu_deviceSEXP);
    rcpp_result_gen = Rcpp::wrap(kodama_opentsne_cpp(indices, distances, init, n_neighbors, perplexity, theta, early_exaggeration_iter, n_iter, early_exaggeration, exaggeration, learning_rate, learning_rate_auto, initial_momentum, final_momentum, min_gain, max_step_norm, n_threads, seed, backend, gpu_device));
    return rcpp_result_gen;
END_RCPP
}
// kodama_graph_cluster_cpp
Rcpp::List kodama_graph_cluster_cpp(Rcpp::IntegerMatrix indices, Rcpp::NumericMatrix distances, std::string method, std::string backend, std::string weight, int n_threads, int n_runs, int n_iterations, int random_walk_steps, int n_clusters, double resolution, double resolution_init, double resolution_delta, double prune, bool mutual, int seed, int gpu_device);
RcppExport SEXP _kodamaR_kodama_graph_cluster_cpp(SEXP indicesSEXP, SEXP distancesSEXP, SEXP methodSEXP, SEXP backendSEXP, SEXP weightSEXP, SEXP n_threadsSEXP, SEXP n_runsSEXP, SEXP n_iterationsSEXP, SEXP random_walk_stepsSEXP, SEXP n_clustersSEXP, SEXP resolutionSEXP, SEXP resolution_initSEXP, SEXP resolution_deltaSEXP, SEXP pruneSEXP, SEXP mutualSEXP, SEXP seedSEXP, SEXP gpu_deviceSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::IntegerMatrix >::type indices(indicesSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type distances(distancesSEXP);
    Rcpp::traits::input_parameter< std::string >::type method(methodSEXP);
    Rcpp::traits::input_parameter< std::string >::type backend(backendSEXP);
    Rcpp::traits::input_parameter< std::string >::type weight(weightSEXP);
    Rcpp::traits::input_parameter< int >::type n_threads(n_threadsSEXP);
    Rcpp::traits::input_parameter< int >::type n_runs(n_runsSEXP);
    Rcpp::traits::input_parameter< int >::type n_iterations(n_iterationsSEXP);
    Rcpp::traits::input_parameter< int >::type random_walk_steps(random_walk_stepsSEXP);
    Rcpp::traits::input_parameter< int >::type n_clusters(n_clustersSEXP);
    Rcpp::traits::input_parameter< double >::type resolution(resolutionSEXP);
    Rcpp::traits::input_parameter< double >::type resolution_init(resolution_initSEXP);
    Rcpp::traits::input_parameter< double >::type resolution_delta(resolution_deltaSEXP);
    Rcpp::traits::input_parameter< double >::type prune(pruneSEXP);
    Rcpp::traits::input_parameter< bool >::type mutual(mutualSEXP);
    Rcpp::traits::input_parameter< int >::type seed(seedSEXP);
    Rcpp::traits::input_parameter< int >::type gpu_device(gpu_deviceSEXP);
    rcpp_result_gen = Rcpp::wrap(kodama_graph_cluster_cpp(indices, distances, method, backend, weight, n_threads, n_runs, n_iterations, random_walk_steps, n_clusters, resolution, resolution_init, resolution_delta, prune, mutual, seed, gpu_device));
    return rcpp_result_gen;
END_RCPP
}
// kodama_embedding_cluster_cpp
Rcpp::List kodama_embedding_cluster_cpp(Rcpp::NumericMatrix embedding, std::string method, std::string backend, std::string graph_backend, std::string weight, std::string metric, int k, int n_threads, int n_runs, int n_iterations, int random_walk_steps, int n_clusters, double resolution, double resolution_init, double resolution_delta, double prune, bool mutual, int seed, int gpu_device);
RcppExport SEXP _kodamaR_kodama_embedding_cluster_cpp(SEXP embeddingSEXP, SEXP methodSEXP, SEXP backendSEXP, SEXP graph_backendSEXP, SEXP weightSEXP, SEXP metricSEXP, SEXP kSEXP, SEXP n_threadsSEXP, SEXP n_runsSEXP, SEXP n_iterationsSEXP, SEXP random_walk_stepsSEXP, SEXP n_clustersSEXP, SEXP resolutionSEXP, SEXP resolution_initSEXP, SEXP resolution_deltaSEXP, SEXP pruneSEXP, SEXP mutualSEXP, SEXP seedSEXP, SEXP gpu_deviceSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type embedding(embeddingSEXP);
    Rcpp::traits::input_parameter< std::string >::type method(methodSEXP);
    Rcpp::traits::input_parameter< std::string >::type backend(backendSEXP);
    Rcpp::traits::input_parameter< std::string >::type graph_backend(graph_backendSEXP);
    Rcpp::traits::input_parameter< std::string >::type weight(weightSEXP);
    Rcpp::traits::input_parameter< std::string >::type metric(metricSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    Rcpp::traits::input_parameter< int >::type n_threads(n_threadsSEXP);
    Rcpp::traits::input_parameter< int >::type n_runs(n_runsSEXP);
    Rcpp::traits::input_parameter< int >::type n_iterations(n_iterationsSEXP);
    Rcpp::traits::input_parameter< int >::type random_walk_steps(random_walk_stepsSEXP);
    Rcpp::traits::input_parameter< int >::type n_clusters(n_clustersSEXP);
    Rcpp::traits::input_parameter< double >::type resolution(resolutionSEXP);
    Rcpp::traits::input_parameter< double >::type resolution_init(resolution_initSEXP);
    Rcpp::traits::input_parameter< double >::type resolution_delta(resolution_deltaSEXP);
    Rcpp::traits::input_parameter< double >::type prune(pruneSEXP);
    Rcpp::traits::input_parameter< bool >::type mutual(mutualSEXP);
    Rcpp::traits::input_parameter< int >::type seed(seedSEXP);
    Rcpp::traits::input_parameter< int >::type gpu_device(gpu_deviceSEXP);
    rcpp_result_gen = Rcpp::wrap(kodama_embedding_cluster_cpp(embedding, method, backend, graph_backend, weight, metric, k, n_threads, n_runs, n_iterations, random_walk_steps, n_clusters, resolution, resolution_init, resolution_delta, prune, mutual, seed, gpu_device));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_kodamaR_kodama_matrix_cpp", (DL_FUNC) &_kodamaR_kodama_matrix_cpp, 22},
    {"_kodamaR_kodama_matrix_graph_cpp", (DL_FUNC) &_kodamaR_kodama_matrix_graph_cpp, 26},
    {"_kodamaR_knncv_cpp", (DL_FUNC) &_kodamaR_knncv_cpp, 11},
    {"_kodamaR_plsldacv_cpp", (DL_FUNC) &_kodamaR_plsldacv_cpp, 12},
    {"_kodamaR_core_knn_cpp", (DL_FUNC) &_kodamaR_core_knn_cpp, 13},
    {"_kodamaR_core_plslda_cpp", (DL_FUNC) &_kodamaR_core_plslda_cpp, 12},
    {"_kodamaR_kodama_knn_graph_cpp", (DL_FUNC) &_kodamaR_kodama_knn_graph_cpp, 6},
    {"_kodamaR_kodama_umap_cpp", (DL_FUNC) &_kodamaR_kodama_umap_cpp, 14},
    {"_kodamaR_kodama_opentsne_cpp", (DL_FUNC) &_kodamaR_kodama_opentsne_cpp, 20},
    {"_kodamaR_kodama_graph_cluster_cpp", (DL_FUNC) &_kodamaR_kodama_graph_cluster_cpp, 17},
    {"_kodamaR_kodama_embedding_cluster_cpp", (DL_FUNC) &_kodamaR_kodama_embedding_cluster_cpp, 19},
    {NULL, NULL, 0}
};

RcppExport void R_init_kodamaR(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
